-- create_dm_user_mariadb.sql
CREATE USER 'tidb-dm'@'%' IDENTIFIED BY 'Pass_1234';
GRANT SELECT, PROCESS, RELOAD, BINLOG MONITOR, REPLICATION SLAVE, REPLICATION SLAVE ADMIN, REPLICATION MASTER ADMIN ON *.* TO 'tidb-dm'@'%';
FLUSH PRIVILEGES;
