-- DM user WITHOUT LOCK TABLES — will fail on full migration
CREATE USER IF NOT EXISTS 'dm_user'@'%' IDENTIFIED BY 'DmPass_1234';
GRANT SELECT, RELOAD, REPLICATION SLAVE, REPLICATION CLIENT ON *.* TO 'dm_user'@'%';
FLUSH PRIVILEGES;
