-- DM user WITHOUT LOCK TABLES — succeeds on vanilla MySQL, fails on RDS
CREATE USER IF NOT EXISTS 'dm_user'@'%' IDENTIFIED BY 'DmPass_1234';
GRANT SELECT, RELOAD, REPLICATION SLAVE, REPLICATION CLIENT ON *.* TO 'dm_user'@'%';
FLUSH PRIVILEGES;
