services:
  core-pd:
    image: alpine:3.20
    command: ["sh", "-c", "sleep infinity"]
  core-tikv:
    image: alpine:3.20
    command: ["sh", "-c", "sleep infinity"]
  core-tidb:
    image: mysql:8.4
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_HOST: "%"
    ports:
      - "3306:3306"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_0900_as_cs
      - --log-bin-trust-function-creators=1
      - --lower_case_table_names=2
      - "--init-connect=SET character_set_client='utf8mb4';SET character_set_results='utf8mb4';SET character_set_connection='utf8mb4';SET collation_connection='utf8mb4_0900_as_cs';"
    tmpfs:
      - /var/lib/mysql
